version: 2
sources:
- name: airbyte_test
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_actions
  - name: _airbyte_raw_audit
  - name: _airbyte_raw_deal
